### ISSUE TITLE
fatal error: config.h: No such file or directory

### ISSUE THREAD

**Issue by thnagahawaththa** [swesterfeld/audiowmark#15]
audiowmark.cc:34:10: fatal error: config.h: No such file or directory
 #include "config.h"
          ^~~~~~~~~~
compilation terminated.

How to fix this initial error?

**Comment by swesterfeld** [comment]
We use automake / autoconf as build system, `config.h` is generated automatically by running `./configure`

So the typical steps to build are
```
./configure
make
make install
```
If you don't have the configure script (which is not included in the git repo), I recommend building from an official release from https://uplex.de/audiowmark/ which includes the configure script.

I assume that you're still trying to build this on Windows. There the whole autoconf / automake build system is problematic (but this is really beyond the scope of this issue). Anyway on Windows either you may need to install extra software (like msys2 or cygwin) to be able to run the configure script.

The alternative would be to add support for a different build system like `cmake`, but this also is non-trivial since it would essentially have to do all the things that are now done using autoconf / automake.

**Comment by thnagahawaththa** [comment]
No sir, On linux system

**Comment by thnagahawaththa** [comment]
It works. Thank you Sir for your guidance
