### ISSUE TITLE
How to decode watermark correctly

### ISSUE THREAD

**Issue by gaga820402** [swesterfeld/audiowmark#25]
Hi
I tested different length waves, but some waves can decoded watermark in one pattern, but other pattern can't find message. Or even can't find message in any pattern. I try use mp3 format but still have this problem.

I saw you said "all pattern combines all data blocks that are available" , I use audiowmark get don't see all pattern.

![image](https://user-images.githubusercontent.com/85274293/195249435-127b3109-9853-4089-9351-bc51250baefe.png)

my wave information ：
![image](https://user-images.githubusercontent.com/85274293/195250224-3f673f27-6567-4b03-ba54-1067070c1cb4.png)

I add watermark by ：audiowmark add oriWave/inshi1.wav newWave/inshi1.wav ecd057f0d1fbb25d6430b338b5d72eb2
![image](https://user-images.githubusercontent.com/85274293/195250095-5742ef93-25f9-41d1-92a2-f7b05b21f8eb.png)

decode watermark by：audiowmark get newWave/inshi1.wav  (only one pattern have message)
![image](https://user-images.githubusercontent.com/85274293/195250141-6925551a-7cfa-4357-a043-76593a53ef05.png)

----------------------------------------------------------------------------------------------------------------------------------------
my wave information ：
![image](https://user-images.githubusercontent.com/85274293/195250770-5bfa1b47-5ab3-453c-a829-a622692308b5.png)

I add watermark by ：audiowmark add oriWave/inshi1.wav newWave/inshi1.wav ecd057f0d1fbb25d6430b338b5d72eb2
![image](https://user-images.githubusercontent.com/85274293/195250711-61afbe8b-d892-4dba-ada1-3163b08ea90d.png)

decode watermark by：audiowmark get newWave/inshi1.wav  (no pattern have message)
![image](https://user-images.githubusercontent.com/85274293/195250681-f0341c1e-badf-4a66-9778-9aac4be119b8.png)

How Can get all pattern?
Why I can't decode correctly?

**Comment by swesterfeld** [comment]
> Why I can't decode correctly?

 - your input files are too short for reliable watermark detection - at the default strength everything should work reliable if 50 seconds are available (see also https://github.com/swesterfeld/audiowmark/issues/20)
 - you are using mono input files, whereas I tested everything with stereo files, for mono input you may need even longer input (or higher strength) for detection to work reliably
 - I tested everything at a sample rate of 44100 Hz (CD quality) - since the watermark is somewhere in the 1000 Hz...5000 Hz range I believe lower sample rates should work, but the second file you used has a sample rate of only 8000 Hz, which might be too low



> How Can get all pattern?

The watermark consists of 50 second blocks, and an all pattern will only be used if more than one of these blocks is available. So if you have 2 minutes of input you'll get one.
